### ISSUE TITLE
Raw error is thrown out on confirmation page, on walletd request error

### ISSUE THREAD

**Issue by fexra** [turtlecoin/woo-turtle#15]
When the plugin sends a invalid request to the walletd, it prints the raw error on the public site, leaking the RCP password. This is a massive security issue
![unknown 2](https://user-images.githubusercontent.com/35935509/40172429-bc462d86-59ce-11e8-905b-d960f0ff9147.png)
.

**Comment by jtnw** [comment]
PR #18 should fix this. Instead of showing the raw rpc command, it only shows "There has been an error processing your request, please try again later."
