### ISSUE TITLE
Improper license

### ISSUE THREAD

**Issue by cryptochangements34** [turtlecoin/woo-turtle#20]
This is clearly a fork of https://github.com/monero-integrations/monerowp and reuses code from that project. This project should therefore reference the original license https://github.com/monero-integrations/monerowp/blob/master/LICENSE

**Comment by RocksteadyTC** [comment]
Fixed, thanks, sorry for any confusion! https://github.com/turtlecoin/woo-turtle/blob/master/LICENSE
